### ISSUE TITLE
pip package on pypi

### ISSUE THREAD

**Issue by ogencoglu** [tum-pbs/ConFIG#1]
Thanks for the interesting work.

A pip package on pypi would be appreciated by the community I think. Any plans for that?

**Comment by qiauil** [comment]
Hello!

Yes, we tried to upload it to Pypi. However, it seems that the package name "ConFIG" is not allowed for Pypi. We might upload our code to PyPi later with a new name in the future. But we would like to keep the current name.

Although it is not available at Pypi now, you can still install ConFIG through `pip install git+https://github.com/tum-pbs/ConFIG` or download the wheel in the release.

Cheers, and enjoy the code.

**Comment by ogencoglu** [comment]
Why do you care about your pip library name to the point that it is preventing you to reach to a bigger userbase because you can't upload to pypi? Biggest ML library in the world has the most stupid name in the history of humankind : huggingface . their pypi library is not called `huggingface` either.

It does not matter if you call it `conflict-free` or `config` or whatever. 

Nobody cares. Focus on the content and science.
