### ISSUE TITLE
Benchmarks with respect to torchjd

### ISSUE THREAD

**Issue by ogencoglu** [tum-pbs/ConFIG#2]
Any plans to have benchmarks with respect to methods in https://github.com/TorchJD/torchjd
?

**Comment by qiauil** [comment]
Hi,

This sounds like an interesting proposal. We will consider including this in the documentation in the next major update if possible.

Cheers
Qiang

**Comment by ogencoglu** [comment]
Any comments on this: https://github.com/TorchJD/torchjd/issues/131#issuecomment-2337218176
?
