### ISSUE TITLE
`latest` should be `least`

### ISSUE THREAD

**Issue by ValerianRey** [tum-pbs/ConFIG#3]
Hey! For the context, I'm starting to look at your code to see if a ConFIG aggregator could be added to TorchJD.

I found something that I think is a typo, but that actually appears in your public interface, so I would recommend to fix it before you have too many users (as the change won't be backward-compatible).

The `use_latest_square` parameter should be `use_least_square` as far as I understand, because it determines whether to use the `torch.linalg.lstsq` function. More generally, I think that the word `latest` is used many times instead of `least`.

**Comment by qiauil** [comment]
Hi， ValerianRey.

Thanks for your comment! You are correct! It is a typo. we will fix it!

**Comment by ogencoglu** [comment]
Where can we follow the integration to torchJD @ValerianRey ? Is there a PR?

**Comment by ValerianRey** [comment]
Hi @ogencoglu!

The discussion about ConFIG is still [here](https://github.com/TorchJD/torchjd/discussions/147) but we haven't really started its implementation so there's no PR yet.

My main concerns were that Pierre never had the time to finish his theoretical analysis of ConFIG (he's extremely busy atm), and that I didn't know what to do with the momentum part of M-ConFIG. In fact, we're not sure of the way we want to handle stateful aggregators for the long term future of torchjd.

However, I can and I should implement the stateless ConFIG (given in Equations 2 and 3). I think it should be fairly easy to do, so I'll try to do that soon.

Out of curiosity, do you plan to use ConFIG through torchjd? I'm trying to understand what our users are looking for!

**Comment by ogencoglu** [comment]
I think many use cases would benefit from a unifying framework (like torchjd) rather than a library for each implementation (dependency hell, lack of long-term support etc.). So, yes, I am planning to compare different approaches to the same problem and ConFIG is one of them. If the abstraction does not exactly fit to torchjd framework for whatever reason, then I will use it from this library.

**Comment by qiauil** [comment]
Hi, @ogencoglu  and @ValerianRey 

I have added a pull request at https://github.com/TorchJD/torchjd/pull/224

As @ValerianRey mentioned, adding the momentum version could be difficult for the torchJD framework. If you want to test the performance of the M-ConFIG method, I would recommend using the current implementation.

Cheers,
Qiang
